# Project information
site_name: Python Synopsis
site_description: Python Study Guide
site_author: Goga Patarkatsishvili 

# Repository
repo_name: ent1c3d/Python-Synopsis
repo_url: https://ent1c3d.github.io/Python-Synopsis/site/

copyright: Copyright &copy; 2017 Goga Patarkatsishvili

# Pages
pages:
    - Home : index.md
    - Beginner:
        - The Python Programming Language, Implementation and Adventages : beginner/Python_Programming_Lanuage.md
        - Python Installation : beginner/Python_Installation.md
        - Start Coding With Python : beginner/Start_Coding_With_Python.md
        - Data Types in Python 3 : beginner/Data_Types_In_Python_3.md
        - Variables and Assignment : beginner/Variables_And_Assignment.md
    - Advanced:
        - Python Metaclasses   : advanced/Python_Metaclasses.md 
    - About: About.md

# Documentation and theme
theme: material
markdown_extensions:
      - fontawesome_markdown
      - codehilite

# Options
extra:
#logo: 'images/logo.PNG'
  palette:
    primary: 'blue grey'
    accent: 'light blue'
#  font:
#    text: 'Roboto'
#    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/ent1c3d'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/ent1c3d/'      